# Python Grundlagen - Einführung in die Welt der Programmierung
Arthur Wohlfahrt & Murphy Sünnenwold

## Was sind Jupyter-Notebooks?

Das hier ist ein sogenanntes Jupyter-Notebook. Notebooks eignen sich besonders als Einstieg, für wissenschaftliche Berichte und interaktive Sessions.
Der Vorteil im Vergleich zu anderen Programmierumgebungen liegt darin, dass Programmbausteine einzeln in sogenannten Zellen ausgeführt werden können. So ist direkt ersichtlich was jede Zeile im Code bewirkt.
Es gibt drei verschiedene Typen von Zellen in Jupyter: Markdown (also formatierter Text), Code und Raw.
Falls die Codeblöcke einen Output (z.B. eine Zahl oder eine Grafik) wird dieser direkt darunter ausgegeben.

Hier ein paar nützliche Shortcuts:
-  Mit "Shift + Enter" führt die den Inhalt der Zelle aus
-  "a"/"b" fügt eine Zelle above oder below der aktuellen ein.
-  "dd" löscht die aktuelle Zelle
-  Ihr könnt Zellen verschieben, trennen und zusammenfügen
-  Mit dem "%" Symbol könnt ihr sog. [Magic-Befehle](https://notebook.community/CestDiego/emacs-ipython-notebook/tests/notebook/nbformat4/Cell%20Magics) verwenden

Zum Vertiefen findet ihr hier die [Jupyter Documentation](https://jupyterlab.readthedocs.io/en/latest/)

## Variabeln

Variablen deklarieren/initialisieren, Datentypen

In [5]:
a = 33 # int (integer)
b = 3.1415926539 # float (floating point number)
hello_world = "Hello World" # str (string)
character = 'a' # char (character)
wahr = True # bool (boolean)
liste = [1, 2, 3] # list
tupel = (1, 2, 3) # tuple
objekt = {"a": 1, "b": 2, "c": 3} # dict (dictionary)

Ausgeben (printing)

In [6]:
print(hello_world)
print(liste)

Hello World
[1, 2, 3]


In [7]:
"Hey Böllis!" # das funktioniert nur hier im "Notebook" Das letzte Statement einer Zelle wird ausgegeben

'Hey Böllis!'

Listen & Dictionaries

In [8]:
print(liste)
print(liste[0])
print(liste[-1])
print(liste[1:3]) 
liste[1] = 1 
print(liste)

[1, 2, 3]
1
3
[2, 3]
[1, 1, 3]


In [9]:
print(objekt)
print(objekt["a"])
objekt["d"] = 4
print(objekt)

{'a': 1, 'b': 2, 'c': 3}
1
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


Mathematische Operationen auf Zahlen

In [10]:
print(a + b)
# + Addition
# - Subtraktion
# * Multiplikation
# / Division
# // Ganzzahlige Division (3//2 = 1)
# ** Potenz (3**2)
# % Modulo (Rest bei Ganzzahliger Division) (3%2 = 1)

36.1415926539


Operationen auf anderen Datentypen (Auswahl)

In [11]:
print(hello_world + "!")
print([1,2]+[3,4])
print(len(liste))

Hello World!
[1, 2, 3, 4]
3


In [12]:
# Error! Dictionaries können nicht addiert werden. Wieso?
print({"a":1,"b":2}+{"b":3,"c":4}) 

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

## Bedingungen

In [13]:
boolean = True

if boolean:
    print("Die Variable a ist wahr")
else:
    print("Die Variable a ist falsch")

Die Variable a ist wahr


In [14]:
zahl = 33

if zahl == 33:
    print("Zahl ist 33")
elif zahl == 34:
    print("Zahl ist 34")
elif zahl == 35:
    print("Zahl ist 35")
else:
    print("Zahl ist weder 33, 34 noch 35")

Zahl ist 33


## Loops (Schleifen)


In [15]:
for item in range(1, 10):
    print(item)

1
2
3
4
5
6
7
8
9


In [16]:
print(liste)
for i in liste:
    print(i + 1)

[1, 1, 3]
2
2
4


In [17]:
i=0
while i<5:
    for j in range(i):
        print(j)
    print("--")
    i+=1

--
0
--
0
1
--
0
1
2
--
0
1
2
3
--


In [18]:
#while True:
#    print("infinite loop")

## Funktionen

In [19]:
print(a,b)

33 3.1415926539


In [20]:
def happy_bday(name,age=22):
    return f"Happy Birthday {name}! You are {age:.1f} years old."

print(happy_bday("Murphy"))
print(happy_bday("Murphy",age=22.78346))

Happy Birthday Murphy! You are 22.0 years old.
Happy Birthday Murphy! You are 22.8 years old.


In [21]:
# was geht hier schief?
def inc(x):
    x += 1 # x = x + 1

a = 1
inc(a)
print(a)

1


## Scoping
Jede Variable hat ihren Scope, also sozusagen ihr Heimatdorf. Dort kennen sie alle mit Namen und es gibt keine zweite, die den gleichen Namen trägt.
Außerhalb des Scopes (oder des Dorfes) kann der gleiche Name jedoch einer anderen Variable gegeben werden. Das ist bei lokalen Variablen der Fall.

Lokale Variablen existieren nur in ihrem lokalen Scope, also z.B. einer Funktion. Nur dort kann auf sie zugegriffen werden
Globale Variablen gibt es hingegen nur einmal im ganzen Programm und sie können von überall gelesen und geschrieben werden.

Achtung Besonderheit bei Jupyter Notebooks!

In [22]:
def funktion():
    h = 20
    
funktion()
print(h)    

NameError: name 'h' is not defined

## Objektorientierung / Klassen
Klassen und Objekte dienen dazu die reale Welt zu erfassen und im Programm abzubilden. So z.B. ein Fahrrad. Seine Eigenschaften wie die Rahmenhoehe oder die Farbe werden als "Attribute" gespeichert.

In [23]:
class Bike:
    # diese Funktion ist der Constructor
    def __init__(self,size:int,color):
        self.size=size # frame size in cm
        self.color=color

    def lackieren(self,new_color):
        self.color=new_color

    def __str__(self):
        return f'{self.color} bike with frame size {self.size}cm.'

    def __repr__(self):
        return f'Bike({self.size}, \"{self.color}\")'

mybike=Bike(57,"silver")  # erstelle eine Instance der Klasse Bike mit dem Constructor
print(mybike.__repr__())
print(mybike)


Bike(57, "silver")
silver bike with frame size 57cm.


In [24]:
print(mybike.color)
mybike.lackieren("yellow")
mybike.color

silver


'yellow'

In [25]:
# Wie Integer oder Strings lassen sich auch Objekte der Klasse "Bike" in eine Liste stecken.
fahrradschuppen = [Bike(30,"orange"),mybike,Bike(50,"black")]
for bike in fahrradschuppen:
    print(bike)

orange bike with frame size 30cm.
yellow bike with frame size 57cm.
black bike with frame size 50cm.


Nicht alle Programmiersprachen benutzen Klassen/sind objektorientiert (Rust z.B.), aber in Python ist das ein wichtiges Konzept.
Vor allem wenn ihr Packages benutzen wollt, solltet ihr die Grundzüge verstanden haben.

## Libraries = Packages = Modules
Was macht ihr, wenn ihr mal nicht weiterwisst oder eine Formel nachschlagen wollt? Ihr geht in die Bibliothek, bzw. ins Internt und schaut nach.
So muss das Rad nicht jedes Mal neu erfunden werden.
Genau das geht in Python auch mit dem Import von packages. Das sind einfach python Dateien mit einer Menge Code und Funktionen, die viele verschiedene Dinge können. Ihr müsst aber nicht alles davon lesen, um damit zu arbeiten, sondern meist nur die Documentation.
Hier ist z.B. die [Numpy Documentation](https://numpy.org/doc/stable/)

In eurer Python Distribution sind bereits viele wichtige Packages enthalten. Mit sog. Package-Managern wie **pip** oder **conda** könnt ihr neue Libraries aus dem Internet installieren und eure Packages auf dem neuesten Stand halten. Es kommen nämlich regelmäig Updates! 

Es kann passieren, dass ihr auch einmal selbst ein Package schreibt. Wenn ihr z.B. eigene Methoden für eure Forschung oder Tätigkeit schreibt, die es so noch nicht gibt und ihr sie anderen zur Verfügung stellen wollt.

In [26]:
# Beispiel aus der Python Standard Library (also vorinstalliert)
#Numpy für effiziente Numerik auf Arrays
import numpy as np # wir benennen numpy in np um, weil wir faul sind
array=np.array([1,2,3,4])
matrix=np.zeros((3,3))
print(matrix)
print(matrix+1)
print(matrix[0,0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0.0


In [27]:
print("mean: ",np.mean(array))
print("log: ",np.log(array))

mean:  2.5
log:  [0.         0.69314718 1.09861229 1.38629436]


In [28]:
import uncertainties

ModuleNotFoundError: No module named 'uncertainties'

**Ups, was ist da passiert?** 

Dieses Package/Module ist noch nicht standdardmäßig installiert
Mit dem Package-Manager könnt ihr ein sog. Environment anlegen, also eine Datei in der die Packages, die Python Distribution und einige andere Dateien liegen. Es bietet sich an für verschiedene Projekte ein eigenes Environment zu erstellen, so könnt ihr verschiedene z.B. verschiedene Python Versionen verwenden und je nach Bedarf andere Packages verwenden.

Auf der Konsole könnt ihr ein Package wie folgt installieren
``` 
my_env/>_ pip install _package_name_
```

## Ausnahmen für Kaefer: Bugs, Errors und Exceptions
Da Computer deterministische Automaten sind, gibt es beim Programmieren feste Regeln. Werden sie verletzt, spuckt der Computer eine Fehlermeldung aus.
Syntaxfehler fliegen direkt beim Compilieren auf. Runtimefehler erst mit Ausfuehrung des Programmes.
Habt ihr einen Logic Error gemacht, dann merkt der Computer nichts davon, euer Programm funktioniert jedoch evtl. nicht wie gewuenscht.

### Syntaxfehler

In [29]:
# was fehlt hier?
# wir verstehen, was gemeint ist, warum tut python das nicht?
print "hello world"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (551328885.py, line 3)

### Runtimefehler

In [30]:
def plus(a,b):
    return a+b
a=1
b=-2
plus(a,c)

NameError: name 'c' is not defined

In [31]:
import math
math.sqrt(b)

ValueError: math domain error

In [32]:
array=np.arange(0,5,0.5)
array[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

### Logic Error

In [33]:
1/0

ZeroDivisionError: division by zero

In [34]:
# keine Fehlermeldung, aber was geht hier schief?
def mittelwert(werte):
    avg=0
    N=len(werte)
    for w in werte:
        avg=avg+w/N
        return avg

mittelwert([1,2,3])

0.3333333333333333

### Exception Handling
[Zum Nachlesen](https://www.geeksforgeeks.org/errors-and-exceptions-in-python/?ref=lbp)

Normalerweise wird die Ausführung des Codes oder der Compiler unterbrochen, wenn ein Fehler auftritt. Einige Fehler lassen sich jedoch antizipieren und so gezielt abfangen und lösen, damit das Programm trotzdem weiter läuft.
Das geschieht mittels **Try & Except** manchmal auch "catch" genannt:

In [35]:
try:
    print(1+"1")
except:
    print("Error")

Error


In [36]:
def bruch(zaehler, nenner):
    try:
        if nenner == 0:
            raise ValueError("Divide by zero")
        else:
            return zaehler/nenner
    except ValueError as e:
        print(e)
    except:
        print("Error")
    print("Fertig berechnet")

bruch("",1)

Error
Fertig berechnet


## Documentation / Code Conventions
Stellt euch vor, ihr muesstet ein Fertigregal ganz ohne Bedienungsanleitung aufbauen. Das ist in etwa aequivalent mit dem Versuch euren nicht dokumentierten Spaghetticode von vor zwei Wochen zu verstehen.
Sauberer, gut dokumentierter Code ist eine Tugend. Fangt daher am besten gleich damit an!
